# Generated by Django 4.2 on 2023-04-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('phonenumber', models.IntegerField()),
                ('mailid', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=250)),
                ('department', models.TextField(max_length=250)),
                ('courses', models.TextField(max_length=250)),
                ('purpose', models.TextField(max_length=250)),
                ('materials', models.TextField(max_length=250)),
            ],
        ),
    ]
