# Generated by Django 4.2 on 2023-04-30 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0002_alter_data_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='department',
        ),
    ]
