# Generated by Django 4.2 on 2023-05-01 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0003_remove_data_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='data',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='data',
            name='purpose',
        ),
    ]
